apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: thred
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db-container
        image: mysql
        ports:
          - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: thRedDb
        - name: MYSQL_ROOT_HOST
          value: '%'
        volumeMounts:
        - name: db-pvc
          mountPath: /var/lib/mysql
      volumes:
      - name: db-pvc
        persistentVolumeClaim:
          claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: thred
spec:
  selector:
    app: db
  type: NodePort
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30001
