version: '3.8'
services:
  database:
    container_name: thred_db
    restart: on-failure
    image: mysql
    environment:
      MYSQL_DATABASE: thRedDb
      MYSQL_ROOT_PASSWORD: thRed2024
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    network_mode: host
  redis:
    container_name: thred_redis
    image: redis
    ports:
      - "6379:6379"
    network_mode: host
volumes:
  mysql_data:
    name: mysql_data
